import{a as S,S as P,i as l}from"./assets/vendor-CIF6YjI2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const B="55975137-aff8e165c0e493ba8aeef9480",q="https://pixabay.com/api/",d=15;async function p(o,r){return(await S.get(q,{params:{key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:d}})).data}const f=document.querySelector(".gallery"),y=document.querySelector(".loader"),E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:t,views:a,comments:b,downloads:v})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <ul class="gallery-info">
          <li><span>Likes</span><span>${t}</span></li>
          <li><span>Views</span><span>${a}</span></li>
          <li><span>Comments</span><span>${b}</span></li>
          <li><span>Downloads</span><span>${v}</span></li>
        </ul>
      </li>`).join("");f.insertAdjacentHTML("beforeend",r),E.refresh()}function M(){f.innerHTML=""}function g(){y.classList.add("loader--visible")}function h(){y.classList.remove("loader--visible")}function $(){loadMoreBtn.classList.remove("is-hidden")}function u(){loadMoreBtn.classList.add("is-hidden")}const O=document.querySelector(".form"),R=document.querySelector(".load-more-btn");let c="",s=1,L=0;O.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(r){c=r,s=1,M(),u(),g();try{const n=await p(c,s);if(L=n.totalHits,n.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(n.hits),w()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}}});R.addEventListener("click",async()=>{s+=1,u(),g();try{const o=await p(c,s);m(o.hits),x(),w()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{h()}});function w(){s*d>=L?(u(),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):$()}function x(){const o=document.querySelector(".gallery-item");if(!o)return;const{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
